version: '3.8'

services:
  language-detection-api:
    build: .
    container_name: language-detection-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=info